### ISSUE TITLE
Svgpp does not compile with Boost 1.63.0

### ISSUE THREAD

**Issue by Firobe** [svgpp/svgpp#51]
Good evening,

With the latest version of Boost (1.63.0), compilation of svgpp fails with the following error when calling document_traversal :
```
svgpp/parser/grammar/transform.hpp:79:41: erreur : no matching function for call to « bind(<unresolved overloaded function type>, const _r1_type&, const _a_type&, const _b_type&) »
                   >> lit(')') [phx::bind(&transform_grammar::call_translate, _r1, _a, _b)]
                                ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
My compiler is GCC 6.3.1. I confirmed that the problem does not appear when using Boost 1.62.0.

I found such an error occurs when transform is included in the processed attributes or when shapes_attributes_by_element is used.

**Comment by Firobe** [comment]
It seems that the problem was due to some functions being overloaded and so their type was ambiguate when binding them.
It seems to work now with some cast to the right type, I created a pull request. There may be some other functions related to this issue that I am not aware of.
