### ISSUE TITLE
SampleTransform02 build error

### ISSUE THREAD

**Issue by osmial** [svgpp/svgpp#59]
Hi I've following build errors when I'm trying to build samples:

 > make SampleTransform02                                                                 
Scanning dependencies of target SampleTransform02                                                                                   
Building CXX object samples/CMakeFiles/SampleTransform02.dir/sample_transform02.cpp.o                                               
In file included from /usr/local/include/boost/numeric/ublas/vector.hpp:21:0,                                                       
                 from /usr/local/include/boost/numeric/ublas/matrix.hpp:18,                                             
                 from /home/tomek/workspace/cpp/svg++/svgpp/src/samples/sample_transform02.cpp:4:                               
/usr/local/include/boost/numeric/ublas/storage.hpp: In member function ‘void boost::numeric::ublas::unbounded_array<T, ALLOC>::serialize(Archive&, unsigned int)’:
/usr/local/include/boost/numeric/ublas/storage.hpp:299:18: error: ‘make_array’ is not a member of ‘boost::serialization’            
             ar & serialization::make_array(data_, s);                                                                              
                  ^~~~~~~~~~~~~                                                                                                     
/usr/local/include/boost/numeric/ublas/storage.hpp: In member function ‘void boost::numeric::ublas::bounded_array<T, N, ALLOC>::serialize(Archive&, unsigned int)’:
/usr/local/include/boost/numeric/ublas/storage.hpp:494:18: error: ‘make_array’ is not a member of ‘boost::serialization’       
             ar & serialization::make_array(data_, s);                                                                              
                  ^~~~~~~~~~~~~                                                                                                     
In file included from /home/tomek/workspace/cpp/svg++/svgpp/src/samples/sample_transform02.cpp:4:0:                                 
/usr/local/include/boost/numeric/ublas/matrix.hpp: In member function ‘void boost::numeric::ublas::c_matrix<T, M, N>::serialize(Archive&, unsigned int)’:
/usr/local/include/boost/numeric/ublas/matrix.hpp:5977:18: error: ‘make_array’ is not a member of ‘boost::serialization’            
             ar & serialization::make_array(data_, N);                                                                              
                  ^~~~~~~~~~~~~

I'm working on Ubuntu 17.04
Boost libs version 1.64.0

**Comment by osmial** [comment]
Based on this discussion:
https://stackoverflow.com/questions/44534516/error-make-array-is-not-a-member-of-boostserialization it looks like it's ublast's issue but this library wasn't updated since 2009 so I've changed SampleTransform02 to be able to build it and created PR.
